VRS:
  train_file: [ '/data/nfs/qiuchen/hyf/datasets/VRSBench/VRS_VQA_train.json' ]
  test_file: [ '/data/nfs/qiuchen/hyf/datasets/VRSBench/VRS_VQA_test.json' ]
  answer_list: '/data/nfs/qiuchen/hyf/datasets/VRSBench/answers_list_test.json'
  vqa_root: '/data/nfs/qiuchen/hyf/datasets/VRSBench/rs_images'

vision_path: '/data/nfs/qiuchen/hyf/pretrained_ckp/vision_pth/deit_base_patch16_224-b5f2ef4d.pth'
image_res: 384      # 480  384  256
batch_size_train: 16
batch_size_test: 8
k_test: 32

alpha: 0.4
distill: True
warm_up: True

eos: '[SEP]'
bert_config: 'configs/config_bert.json'

# optimizer
init_lr: 2e-5
weight_decay: 0.05
#min_lr: 0
min_lr: 1e-8
max_epoch: 10
